# Generated by Django 4.2.5 on 2024-02-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=60)),
                ('teg1', models.CharField(max_length=25)),
                ('teg2', models.CharField(max_length=25)),
                ('teg3', models.CharField(max_length=25)),
                ('teg4', models.CharField(max_length=25)),
                ('teg5', models.CharField(max_length=25)),
                ('see_all', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.UUIDField()),
                ('nickname', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('age', models.DateField()),
            ],
        ),
    ]
