# Generated by Django 4.2.5 on 2024-03-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_user_id_alter_user_id_user_messege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='teg1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='teg2',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='teg3',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='teg4',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='teg5',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
