# Generated by Django 4.2.5 on 2024-03-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_image_teg1_alter_image_teg2_alter_image_teg3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='teg1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='teg2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='teg3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='teg4',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='teg5',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
