# Generated by Django 4.2.5 on 2024-05-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_user_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='see_all',
        ),
    ]
