# Generated by Django 4.2.5 on 2024-05-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_image_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
