# Generated by Django 4.2.5 on 2024-05-29 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='pictures/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])]),
        ),
    ]
