# Generated by Django 4.2.5 on 2024-05-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_alter_image_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
    ]
